"""
=============================================================================
SCRIPT NAME: build_factor_reference.py
=============================================================================

INPUT FILES:
- Data/cache/query_assistant/duckdb_schema.json
- Data/cache/query_assistant/variable_catalog.json
- Data/cache/query_assistant/neo4j_schema.json
    All produced by scripts/build_schema_registry.py.

OUTPUT FILES:
- docs/factor_reference.md
    Comprehensive AI-readable reference: every DuckDB table with row counts
    and date ranges; every variable organized by source with frequency,
    coverage, and normalization variants; the full Neo4j graph map (every
    node label, every relationship type, every index).

VERSION: 1.0
LAST UPDATED: 2026-04-29
AUTHOR: Arjun Divecha (with Claude)

DESCRIPTION:
Generates docs/factor_reference.md from the live schema cache. The cache
is the single source of truth — it's regenerated by build_schema_registry.py
during every monthly_update run, so this reference doc stays current as
long as you re-run this script after the cache refresh.

For small panels (<=100 variables) every variable is listed individually
with its source, frequency, date range, country coverage, and whether
_CS / _TS normalized variants exist. For large panels (gdelt_panel with
~2,300 variables) we collapse into prefix-family groupings with counts
and 10 sample names per family — listing 2,300 lines of theme variables
in a reference doc would help nobody.

The Neo4j section dumps every label, every relationship, every property
key, and every index in full — that surface is small (7 labels, ~10
relationships) so completeness trumps brevity.

DEPENDENCIES:
- pandas (only used incidentally; no SQL access required — reads JSON only)

USAGE:
  python scripts/build_factor_reference.py
  python scripts/build_factor_reference.py --output docs/custom_path.md

NOTES:
- Re-run after build_schema_registry.py for an up-to-date catalog.
- Designed for AI readers as much as humans: structure is parseable,
  variable lists are predictable, no rendering tricks.
=============================================================================
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

BASE_DIR = Path(__file__).resolve().parent.parent
CACHE_DIR = BASE_DIR / "Data" / "cache" / "query_assistant"
DEFAULT_OUTPUT = BASE_DIR / "docs" / "factor_reference.md"

DUCKDB_PATH = CACHE_DIR / "duckdb_schema.json"
VARIABLE_PATH = CACHE_DIR / "variable_catalog.json"
NEO4J_PATH = CACHE_DIR / "neo4j_schema.json"

# Threshold above which a panel is treated as "large" — variables get
# grouped by prefix family rather than listed exhaustively.
LARGE_PANEL_THRESHOLD = 100

# Prefix → family display name. Used for grouping large panels (gdelt).
GDELT_FAMILIES = [
    ("theme_",   "Theme attention (GDELT GKG themes)"),
    ("gcam_",    "GCAM emotional dimensions"),
    ("event_",   "Event aggregates (GDELT EVENTS / EVENTMENTIONS)"),
]
GDELT_CORE_TONE_MARKERS = (
    "metronome", "monthly_risk", "monthly_defensive", "sentiment_", "attention_",
    "risk_fast", "dispersion_fast", "local_tone", "foreign_tone", "local_foreign_gap",
    "tone_", "country_news_", "n_articles", "polarity", "positive_", "negative_",
    "local_attention", "lf_gap", "attention_shock", "monthly_metronome",
)


def load_caches() -> tuple[dict, dict, dict]:
    duckdb_schema = json.loads(DUCKDB_PATH.read_text())
    variable_catalog = json.loads(VARIABLE_PATH.read_text())
    neo4j_schema = json.loads(NEO4J_PATH.read_text())
    return duckdb_schema, variable_catalog, neo4j_schema


def fmt_date_range(table_info: dict) -> str:
    dr = table_info.get("date_range") or {}
    if dr.get("min") and dr.get("max"):
        return f"{dr['min']} → {dr['max']}"
    return "—"


def variable_metadata_for_source(catalog: dict, source: str) -> List[dict]:
    """Return every variable whose `source` matches, sorted by name."""
    metadata = catalog.get("variable_metadata", {})
    rows = []
    for name, meta in metadata.items():
        if meta.get("source") != source:
            continue
        rows.append(meta)
    rows.sort(key=lambda m: m["variable"])
    return rows


def variable_metadata_for_table(
    catalog: dict, duckdb_schema: dict, table_name: str
) -> List[dict]:
    """Map a DuckDB table to its variables via sources observed in that table.

    For raw factor tables we use the table's `column_value_samples.source` if
    populated (gives source values directly). Falls back to scanning all
    variables grouped by source.
    """
    table_info = duckdb_schema.get("tables", {}).get(table_name, {})
    sample = table_info.get("column_value_samples", {}) or {}
    sources_in_table = set(sample.get("source", []) or [])
    metadata = catalog.get("variable_metadata", {})

    rows = []
    if sources_in_table:
        for name, meta in metadata.items():
            if meta.get("source") in sources_in_table:
                rows.append(meta)
    else:
        # Fallback: just use sample_variables in the table info
        for v in table_info.get("sample_variables", []) or []:
            if v in metadata:
                rows.append(metadata[v])
    rows.sort(key=lambda m: m["variable"])
    return rows


def render_variable_row(meta: dict, with_norm: bool = True) -> str:
    """One markdown table row for a variable."""
    name = meta["variable"]
    src = meta.get("source", "")
    freq = meta.get("frequency", "")
    cc = meta.get("country_count", "")
    fd = meta.get("first_date", "") or ""
    ld = meta.get("last_date", "") or ""
    norm = meta.get("normalization", "raw")
    forecast = "✓" if meta.get("is_forecast") else ""
    sparse = "✓" if meta.get("is_sparse") else ""
    cells = [
        f"`{name}`", src, freq, str(cc),
        f"{fd} → {ld}" if fd or ld else "—",
    ]
    if with_norm:
        cells.extend([norm, sparse, forecast])
    return "| " + " | ".join(cells) + " |"


def variable_table_header(with_norm: bool = True) -> List[str]:
    head = ["Variable", "Source", "Frequency", "Countries", "Date range"]
    if with_norm:
        head.extend(["Norm", "Sparse", "Forecast"])
    sep = ["---"] * len(head)
    return [
        "| " + " | ".join(head) + " |",
        "| " + " | ".join(sep) + " |",
    ]


def categorize_gdelt_variable(name: str) -> str:
    for prefix, label in GDELT_FAMILIES:
        if name.startswith(prefix):
            return label
    if any(marker in name for marker in GDELT_CORE_TONE_MARKERS):
        return "Core tone signals (shallow GDELT pipeline)"
    return "Other"


def render_large_panel(
    title: str, rows: List[dict], anchor_note: str | None = None
) -> List[str]:
    """For a panel with > LARGE_PANEL_THRESHOLD vars: group by family + samples."""
    out = [f"### {title}", ""]
    if anchor_note:
        out.append(anchor_note)
        out.append("")
    out.append(f"**Total variables:** {len(rows):,}")
    out.append("")

    families: Dict[str, List[dict]] = defaultdict(list)
    for r in rows:
        families[categorize_gdelt_variable(r["variable"])].append(r)

    for fam, group in sorted(families.items(), key=lambda kv: -len(kv[1])):
        out.append(f"**{fam}** — {len(group)} variables")
        sample_names = sorted([r["variable"] for r in group])
        sample_show = sample_names[:10]
        sample_str = ", ".join(f"`{n}`" for n in sample_show)
        suffix = f", +{len(group) - 10} more" if len(group) > 10 else ""
        out.append(f"- Samples: {sample_str}{suffix}")
        if group:
            r = group[0]
            out.append(
                f"- Frequency: {r.get('frequency', '—')} · "
                f"Country coverage: up to {max(g.get('country_count', 0) for g in group)} countries"
            )
        out.append("")
    return out


def render_small_panel(title: str, rows: List[dict]) -> List[str]:
    """For a panel with <= LARGE_PANEL_THRESHOLD vars: list every variable."""
    out = [f"### {title}", ""]
    out.append(f"**Total variables:** {len(rows)}")
    out.append("")
    out.extend(variable_table_header(with_norm=True))
    for r in rows:
        out.append(render_variable_row(r, with_norm=True))
    out.append("")
    return out


def render_panel(title: str, rows: List[dict], note: str | None = None) -> List[str]:
    if not rows:
        return [f"### {title}", "", "*No variables listed in current schema cache.*", ""]
    if len(rows) > LARGE_PANEL_THRESHOLD:
        return render_large_panel(title, rows, anchor_note=note)
    return render_small_panel(title, rows) if note is None else [f"### {title}", "", note, ""] + render_small_panel(title, rows)[1:]


def render_duckdb_overview(duckdb_schema: dict) -> List[str]:
    out = ["## DuckDB Tables", ""]
    out.append("Every analytical surface in `Data/asado.duckdb`. The `t2_master`/`t2_raw` tables are sourced from `T2 Master.xlsx` (separate Bloomberg-driven pipeline); everything else is built by ASADO collectors.")
    out.append("")
    out.extend([
        "| Table | Type | Rows | Date range | Description |",
        "| --- | --- | --- | --- | --- |",
    ])
    for name, info in sorted(duckdb_schema.get("tables", {}).items()):
        rt = info.get("table_type") or ""
        rc = info.get("row_count") or 0
        rng = fmt_date_range(info)
        desc = (info.get("description") or "").replace("\n", " ")
        if len(desc) > 220:
            desc = desc[:217] + "…"
        out.append(f"| `{name}` | {rt} | {rc:,} | {rng} | {desc} |")
    out.append("")
    return out


def render_neo4j(neo4j_schema: dict) -> List[str]:
    out = ["## Neo4j Knowledge Graph", ""]
    if not neo4j_schema.get("available"):
        out.append("*Neo4j was unreachable when the schema cache was built — run `scripts/build_schema_registry.py` with Neo4j up to populate this section.*")
        out.append("")
        return out

    out.append(f"**URI:** `{neo4j_schema.get('uri')}`")
    out.append("")

    # Labels
    labels = neo4j_schema.get("labels", {}) or {}
    out.append(f"### Node labels ({len(labels)})")
    out.append("")
    for label, info in sorted(labels.items()):
        count = info.get("count", "?")
        desc = (info.get("description") or "").replace("\n", " ")
        out.append(f"#### `:{label}` — {count:,} nodes" if isinstance(count, int) else f"#### `:{label}`")
        if desc:
            out.append("")
            out.append(desc)
        props = info.get("properties") or []
        if props:
            out.append("")
            out.append("Properties:")
            for prop in props:
                key = prop.get("key", "")
                ptype = prop.get("type") or prop.get("data_type") or ""
                pdesc = (prop.get("description") or "").strip()
                line = f"- `{key}`"
                if ptype:
                    line += f" ({ptype})"
                if pdesc:
                    line += f" — {pdesc}"
                out.append(line)
        out.append("")

    # Relationships
    rels = neo4j_schema.get("relationships", {}) or {}
    out.append(f"### Relationship types ({len(rels)})")
    out.append("")
    out.extend([
        "| Relationship | Count | From → To | Description |",
        "| --- | --- | --- | --- |",
    ])
    for rname, info in sorted(rels.items()):
        count = info.get("count", "?")
        src = ", ".join(info.get("source_labels") or [])
        tgt = ", ".join(info.get("target_labels") or [])
        desc = (info.get("description") or "").replace("\n", " ")
        if len(desc) > 200:
            desc = desc[:197] + "…"
        count_str = f"{count:,}" if isinstance(count, int) else str(count)
        out.append(f"| `[:{rname}]` | {count_str} | {src} → {tgt} | {desc} |")
    out.append("")

    # Indexes
    indexes = neo4j_schema.get("indexes", []) or []
    if indexes:
        out.append(f"### Indexes ({len(indexes)})")
        out.append("")
        out.extend([
            "| Name | Type | Label | Properties |",
            "| --- | --- | --- | --- |",
        ])
        for idx in indexes:
            iname = idx.get("name", "")
            itype = idx.get("type", "")
            ilabel = ", ".join(idx.get("labels", []) or [])
            iprops = ", ".join(idx.get("properties", []) or [])
            out.append(f"| `{iname}` | {itype} | {ilabel} | {iprops} |")
        out.append("")
    return out


def render_indexes(duckdb_schema: dict) -> List[str]:
    out = ["## DuckDB Indexes", ""]
    indexes = duckdb_schema.get("indexes", []) or []
    if not indexes:
        out.append("*No indexes recorded in schema cache.*")
        out.append("")
        return out
    out.extend([
        "| Index | Table | Expression |",
        "| --- | --- | --- |",
    ])
    for idx in indexes:
        out.append(
            f"| `{idx.get('index_name','')}` | "
            f"`{idx.get('table_name','')}` | "
            f"{idx.get('expressions','')} |"
        )
    out.append("")
    return out


def render_overview(duckdb_schema: dict, catalog: dict, neo4j_schema: dict) -> List[str]:
    out = ["## At a glance", ""]
    n_tables = len(duckdb_schema.get("tables", {}))
    factor_surface = catalog.get("factor_surface") or duckdb_schema.get("factor_surface") or "feature_panel"
    n_vars_total = catalog.get("variable_count", 0)
    n_vars_raw = sum(
        1 for m in catalog.get("variable_metadata", {}).values()
        if m.get("normalization") == "raw"
    )
    n_vars_cs = sum(
        1 for m in catalog.get("variable_metadata", {}).values()
        if m.get("normalization") == "cs"
    )
    n_vars_ts = sum(
        1 for m in catalog.get("variable_metadata", {}).values()
        if m.get("normalization") == "ts"
    )
    n_labels = len(neo4j_schema.get("labels", {}) or {})
    n_rels = len(neo4j_schema.get("relationships", {}) or {})
    out.append(f"- **DuckDB tables / views:** {n_tables}")
    out.append(f"- **Distinct variables in `{factor_surface}` catalog:** {n_vars_total:,}")
    out.append(f"  - Raw: {n_vars_raw:,} · `_CS` cross-sectional: {n_vars_cs:,} · `_TS` time-series: {n_vars_ts:,}")
    out.append(f"- **Neo4j node labels:** {n_labels}")
    out.append(f"- **Neo4j relationship types:** {n_rels}")
    out.append(f"- **Country universe:** {len(duckdb_schema.get('countries', []))} (T2 names)")
    out.append("")
    return out


def render_variants_explainer() -> List[str]:
    return [
        "## A note on `_CS` / `_TS` variants",
        "",
        "Many raw variables are accompanied by two normalized variants in the `normalized_panel` view:",
        "",
        "- **`_CS` (cross-sectional)** — z-score within the same date across countries. Removes global trends; high values = country looks attractive *vs. peers this month*.",
        "- **`_TS` (time-series)** — rolling z-score within the same country across time. Removes country-specific levels; high values = country looks attractive *vs. its own history*.",
        "",
        "The optimizer pipelines (T2 Econ, T2 GDELT) construct factor returns separately for each variant — they're treated as distinct variables, not interchangeable views of one another. `factor_returns.factor` retains the suffix for this reason.",
        "",
    ]


def render_variables_section(catalog: dict) -> List[str]:
    """Group every variable by source, render per-source tables."""
    out = ["## Variables by source", ""]
    out.append("Variables in this section are listed at the *raw* level (no `_CS`/`_TS` suffix). For each raw variable, the `normalized_panel` may also expose `_CS` and `_TS` variants — see explainer above.")
    out.append("")
    sources_seen: Dict[str, List[dict]] = defaultdict(list)
    for name, meta in catalog.get("variable_metadata", {}).items():
        if meta.get("normalization") != "raw":
            continue
        sources_seen[meta.get("source", "unknown")].append(meta)

    # Group sources roughly by panel for ordering
    SOURCE_ORDER = [
        # T2 (external)
        "t2", "t2_raw",
        # external_factors
        "epu", "gpr", "bis_credit", "bis_property", "bis_reer", "oecd", "worldbank",
        # extended_factors
        "bis_policy_rate", "bis_debt_service", "ecb_fx", "fred", "ndgain",
        "ofac", "undp_hdi", "ilostat", "eia", "faostat",
        "oecd_bci", "oecd_cci", "oecd_household_dashboard", "oecd_institutional_investors",
        # imf_factors
        "imf_cpi", "imf_weo", "imf_bop", "imf_er", "imf_itg", "imf_ls",
        "imf_mfs_ir", "imf_fsi",
        # macrostructure
        "macrostructure_derived", "qpsd", "portfolio_ownership",
        # bloomberg
        "bloomberg",
        # gdelt
        "gdelt", "gdelt_deep_theme", "gdelt_deep_gcam", "gdelt_deep_event",
    ]
    seen = set()
    for src in SOURCE_ORDER:
        if src in sources_seen:
            seen.add(src)
            out.extend(render_panel(f"`{src}`", sources_seen[src]))
    # Any sources not in our ordered list, append alphabetically
    for src in sorted(sources_seen):
        if src in seen:
            continue
        out.extend(render_panel(f"`{src}`", sources_seen[src]))
    return out


def render_header(catalog: dict, duckdb_schema: dict) -> List[str]:
    return [
        "# ASADO Factor Reference",
        "",
        f"_Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_",
        f"_Source of truth: `Data/cache/query_assistant/` — refreshed by `scripts/build_schema_registry.py` on every monthly update._",
        "",
        "This document is intended to be read end-to-end by an AI agent (or human) who needs to understand exactly what the ASADO warehouse contains, what each surface means, and how to compose queries against it. Keep prose minimal; lean on tables.",
        "",
        "Authoritative companion docs:",
        "- `README.md` — operational entry point (commands, monthly update, MCP setup)",
        "- `CLAUDE.md` — agent-facing project conventions",
        "- `docs/factor_reference.md` (this file) — full DB + variable + graph reference",
        "",
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                        help=f"Output markdown path (default: {DEFAULT_OUTPUT})")
    args = parser.parse_args()

    duckdb_schema, catalog, neo4j_schema = load_caches()

    parts: List[str] = []
    parts.extend(render_header(catalog, duckdb_schema))
    parts.extend(render_overview(duckdb_schema, catalog, neo4j_schema))
    parts.extend(render_duckdb_overview(duckdb_schema))
    parts.extend(render_variants_explainer())
    parts.extend(render_variables_section(catalog))
    parts.extend(render_neo4j(neo4j_schema))
    parts.extend(render_indexes(duckdb_schema))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(parts))
    n_lines = len(parts)
    n_bytes = args.output.stat().st_size
    print(f"Wrote {args.output}  ({n_lines:,} lines, {n_bytes/1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
