#!/usr/bin/env python3
"""
=============================================================================
SCRIPT NAME: scripts/build_t2_master.py
=============================================================================

INPUT FILES:
- /Users/arjundivecha/Dropbox/AAA Backup/A Working/ASADO/Data/work/t2/
    T2 Bloomberg Master.xlsx
    Bloomberg master workbook — GENERATED by ASADO each monthly run via
    scripts/collect_t2_bloomberg.py (live blpapi pull), replacing the old
    hand-maintained dump "Country Bloomberg Data Master T.xlsx". Required sheets:
      Tot Return Index, PX_LAST, 120MA, Gold, Copper, Oil, Agriculture,
      Currency, 10Yr Bond, Best EPS, Trailing EPS

- /Users/arjundivecha/Dropbox/AAA Backup/A Working/ASADO/Data/work/t2/
    AssetList.xlsx  — country ETF tickers for P2P score calculation

OUTPUT FILES:
- /Users/arjundivecha/Dropbox/AAA Backup/A Working/ASADO/Data/work/t2/
    P2P_Country_Historical_Scores.xlsx  — monthly P2P scores (yfinance)
    T2 Master.xlsx                      — final master file
- /Users/arjundivecha/Dropbox/AAA Backup/A Working/ASADO/Data/work/gdelt/
    T2 Master.xlsx
- /Users/arjundivecha/Dropbox/AAA Backup/A Working/ASADO/Data/work/econ/
    T2 Master.xlsx

VERSION: 1.2
LAST UPDATED: 2026-08-21
AUTHOR: Arjun Divecha (with Claude)

DESCRIPTION:
Two-phase pipeline that produces T2 Master.xlsx and distributes it to all
active T2 pipeline directories.

Phase 1 — P2P Scores (from Step Zero Create P2P Scores.py):
  Downloads monthly country ETF price data via yfinance.
  Computes Price-to-Peak (P2P) momentum scores for each country-month:
    score = (price / 12m_rolling_max) × R² × sign(slope)
  Writes P2P_Country_Historical_Scores.xlsx to T2 Factor Timing Fuzzy.

Phase 2 — T2 Master (from Step One Create T2Master.py):
  Reads T2 Bloomberg Master.xlsx (ASADO-generated from live blpapi).
  Computes forward returns (1M/3M/6M/9M/12M), trailing returns (1M/3M/12M),
  12-1M spread, FX/bond changes, commodity BETAS, 120MA signal, merges P2P.

  COMMODITY SEMANTIC BREAK, 2026-08-21 (v1.2) -- read this before comparing
  any output to a pre-2026-08-21 T2 Master or applying an older verdict:
    Gold, Copper, Oil, Agriculture
        WAS  the raw commodity price, broadcast identically to all 34 countries
        NOW  each country's trailing beta to that commodity
             (rolling 120 months, min_periods 36, on 1M total returns)
    Gold 12, Copper 12, Oil 12, Agriculture 12
        WAS  the 12-month change in the commodity price (identical per country)
        NOW  that country's beta x the commodity's 12-month return
  The old form had ZERO cross-sectional dispersion, so Gold_CS / Copper_CS /
  Oil_CS / Agriculture_CS were 0/0 and carried no information. Any loop-DB
  verdict or graveyard entry on those eight variable names was earned under
  the OLD semantics and does not transfer.
  Ported from "A Complete/T2 Factor Timing Fuzzy/Step One Create T2Master.py"
  (commit 397207b), with the backfilled first 120 months replaced by an honest
  min_periods=36 burn-in. See _commodity_betas for the measurement.
  Writes T2 Master.xlsx to T2 Factor Timing Fuzzy, T2 GDELT, and T2 Econ.

DEPENDENCIES:
- pandas, numpy, scipy, openpyxl, xlsxwriter, yfinance, python-dateutil

USAGE:
  python scripts/build_t2_master.py              # full run (P2P + T2 Master)
  python scripts/build_t2_master.py --skip-p2p   # use existing P2P file, rebuild T2 Master only
  python scripts/build_t2_master.py --dry-run    # preview, no writes
  python scripts/build_t2_master.py --check      # report on existing output files

NOTES:
- Phase 1 requires internet access (yfinance). Use --skip-p2p if offline.
- Phase 2 reads T2 Bloomberg Master.xlsx, generated upstream in the monthly
  pipeline by scripts/collect_t2_bloomberg.py (Bloomberg Terminal must be up).
- T2 Master.xlsx is written to three directories; all three or none are updated.
- On failure, existing T2 Master.xlsx files are left untouched (no partial writes).
=============================================================================
"""

from __future__ import annotations

import argparse
import logging
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from dateutil.relativedelta import relativedelta
from scipy.stats import linregress

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "Data"

# ── Internalized work paths ───────────────────────────────────────────────────
T2_FUZZY_DIR = Path(
    "/Users/arjundivecha/Dropbox/AAA Backup/A Working/ASADO/Data/work/t2"
)
T2_GDELT_DIR = Path(
    "/Users/arjundivecha/Dropbox/AAA Backup/A Working/ASADO/Data/work/gdelt"
)
T2_ECON_DIR = Path(
    "/Users/arjundivecha/Dropbox/AAA Backup/A Working/ASADO/Data/work/econ"
)

# T2 Bloomberg master workbook — now GENERATED by ASADO itself
# (scripts/collect_t2_bloomberg.py pulls it live from blpapi every monthly run),
# NOT the old hand-maintained Excel dump "Country Bloomberg Data Master T.xlsx".
BLOOMBERG_FILE = T2_FUZZY_DIR / "T2 Bloomberg Master.xlsx"

ASSET_LIST_FILE = T2_FUZZY_DIR / "AssetList.xlsx"
P2P_FILE = T2_FUZZY_DIR / "P2P_Country_Historical_Scores.xlsx"

T2_MASTER_DESTINATIONS = [
    T2_FUZZY_DIR / "T2 Master.xlsx",
    T2_GDELT_DIR / "T2 Master.xlsx",
    T2_ECON_DIR  / "T2 Master.xlsx",
]

# ── Country name list (T2 canonical order, 'Country' = date column header) ───
COUNTRY_NAMES = [
    'Country', 'Singapore', 'Australia', 'Canada', 'Germany', 'Japan',
    'Switzerland', 'U.K.', 'NASDAQ', 'U.S.', 'France', 'Netherlands',
    'Sweden', 'Italy', 'ChinaA', 'Chile', 'Indonesia', 'Philippines',
    'Poland', 'US SmallCap', 'Malaysia', 'Taiwan', 'Mexico', 'Korea',
    'Brazil', 'South Africa', 'Denmark', 'India', 'ChinaH', 'Hong Kong',
    'Thailand', 'Turkey', 'Spain', 'Vietnam', 'Saudi Arabia',
]

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler()],
)
logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 1 — P2P Score calculation (yfinance)
# ═══════════════════════════════════════════════════════════════════════════════

def _p2p_score(prices: pd.Series) -> Optional[float]:
    """Price-to-Peak momentum score = (price/12m_max) × R² × sign(slope)."""
    if len(prices) < 2:
        return None
    max_price = prices.rolling(window=12, min_periods=1).max()
    price_to_peak = prices / max_price
    x = np.arange(len(prices))
    slope, _, r_value, _, _ = linregress(x, prices)
    return float(price_to_peak.iloc[-1] * r_value**2 * (1 if slope > 0 else -1))


def build_p2p_scores() -> pd.DataFrame:
    """
    Download monthly ETF prices via yfinance and compute historical P2P scores.
    Returns a DataFrame with 'Unnamed: 0' (date) column + one column per ticker.
    """
    import yfinance as yf
    import warnings
    warnings.filterwarnings("ignore")

    if not ASSET_LIST_FILE.exists():
        raise FileNotFoundError(f"AssetList not found: {ASSET_LIST_FILE}")

    asset_list = pd.read_excel(ASSET_LIST_FILE)
    tickers = [str(t).strip().upper() for t in asset_list.iloc[:, 0] if pd.notna(t)]
    logger.info("P2P: downloading %d tickers via yfinance ...", len(tickers))

    data_start = pd.to_datetime("2000-01-01") - relativedelta(months=12)

    # Download SPY first to establish the index
    spy = yf.download("SPY", start=data_start, interval="1mo", progress=False)["Close"]
    spy.index = spy.index.tz_localize(None)
    all_prices = pd.DataFrame(index=spy.index)
    all_prices["SPY"] = spy

    for ticker in tickers:
        try:
            data = yf.download(ticker, start=data_start, interval="1mo", progress=False)["Close"]
            data.index = data.index.tz_localize(None)
            if not data.empty:
                all_prices[ticker] = data
        except Exception:
            continue

    logger.info("P2P: downloaded prices for %d tickers", len(all_prices.columns) - 1)

    # Compute monthly P2P scores from month 12 onward
    p2p_scores = pd.DataFrame(index=all_prices.index)
    start_ts = pd.to_datetime("2000-01-01")

    for i in range(12, len(all_prices)):
        dt = all_prices.index[i]
        for ticker in tickers:
            if ticker in all_prices.columns:
                window = all_prices[ticker].iloc[i - 12 : i + 1]
                if not window.isna().any() and len(window) > 1:
                    score = _p2p_score(window)
                    if score is not None:
                        p2p_scores.loc[dt, ticker] = score

    p2p_scores = p2p_scores[p2p_scores.index >= start_ts]
    p2p_scores = p2p_scores.reset_index()
    p2p_scores = p2p_scores.rename(columns={"index": "Unnamed: 0"})

    logger.info("P2P: computed scores for %d months, %d tickers",
                len(p2p_scores), len(p2p_scores.columns) - 1)
    return p2p_scores


def save_p2p(p2p_df: pd.DataFrame) -> None:
    with pd.ExcelWriter(str(P2P_FILE), engine="xlsxwriter") as writer:
        p2p_df.to_excel(writer, sheet_name="Sheet1", index=False)
        wb = writer.book
        ws = writer.sheets["Sheet1"]
        date_fmt = wb.add_format({"num_format": "yyyy-mm-dd"})
        ws.set_column(0, 0, 12, date_fmt)
        ws.set_column(1, len(p2p_df.columns) - 1, 8)
    logger.info("P2P scores saved: %s", P2P_FILE)


# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2 — T2 Master generation (Bloomberg data + P2P)
# ═══════════════════════════════════════════════════════════════════════════════

def _standardize_date(df: pd.DataFrame) -> pd.DataFrame:
    """Shift dates to first of next month (Bloomberg convention → T2 convention)."""
    try:
        df = df.copy()
        df["Country"] = pd.to_datetime(df["Country"], errors="raise")
        df["Country"] = (df["Country"].dt.to_period("M") + 1).dt.to_timestamp()
    except (ValueError, pd.errors.ParserError):
        logger.warning("Could not parse 'Country' column as dates — skipping date standardization")
    return df


# ── Outlier handling ─────────────────────────────────────────────────────────
# REPLACED 2026-08-21 (Arjun's decision, option (b) of
# docs/T2_CAUSAL_CLEANING_2026-08-21.md). What was here until now:
#
#   _winsorize            clipped every observation to bounds from the
#                         FULL-SAMPLE median and MAD, so whether a 2008 point
#                         was clipped depended on 2024 data.
#   _check_local_outliers judged point i against a CENTRED +/-20-month window
#                         and replaced it with a mean including the 20 months
#                         AFTER it.
#
# Both were look-ahead, and the cleaned sheets reach unified_panel as
# source='t2' (30.6% of feature_panel), so the leak reached harness verdicts.
#
# The obvious repair -- make the same statistics causal -- was implemented,
# measured and REJECTED: median +/- k*MAD clipping of a RETAINED LEVEL is
# ill-posed for a trending series. The full-sample version only escaped it
# because the full-sample median sits mid-trend, which IS the look-ahead. Made
# causal the band anchors on the early sample and shears off the later trend
# (13.5% of Copper, 9.7% of Oil clipped). Rolling-60/120 did not rescue it.
#
# So the winsorizer is GONE, not made causal. What remains is a single causal
# spike guard whose only job is catching fat-fingers. Measured on the real
# workbook, over the sheets actually cleaned after the commodity-beta port, it
# touches 0.260% of cells versus 0.910% for the leaking rule it replaces --
# causal AND about 3.5x gentler.
#
# Two details that matter:
#   * strictly PRIOR window -- a causal detector cannot wait for the future to
#     confirm a new level.
#   * CLIP TO THE BAND EDGE, never replace with the trailing mean. Replacing
#     turns every genuine regime shift into data destruction, because the
#     detector cannot tell a spike from a step. Clipping keeps the direction
#     and most of the magnitude of a real move.
SPIKE_SPAN = 20            # EWM span of the trailing window
SPIKE_SIGMA = 6.0          # deviations before a point is treated as a spike
SPIKE_MIN_HISTORY = 10     # prior observations required before the guard arms


def _causal_spike_clips(
    series: pd.Series,
    span: int = SPIKE_SPAN,
    sigma: float = SPIKE_SIGMA,
    min_history: int = SPIKE_MIN_HISTORY,
) -> List[Dict]:
    """Points more than `sigma` trailing EWM deviations from the trailing mean.

    Returns [{"index": i, "new_value": clipped}] computed from ONLY series[:i].
    """
    series = series.astype("float64")
    out: List[Dict] = []
    for i in range(len(series)):
        window = series[max(0, i - span):i]      # strictly prior
        if len(window) < min_history:
            continue
        mean = window.ewm(span=span).mean().iloc[-1]
        std = window.ewm(span=span).std().iloc[-1]
        if not np.isfinite(std) or std <= np.finfo(float).eps:
            continue
        value = series.iloc[i]
        if not np.isfinite(value):
            continue
        z = (value - mean) / std
        if abs(z) > sigma:
            out.append({"index": i, "new_value": float(mean + np.sign(z) * sigma * std)})
    return out


def _clean_sheet(data: pd.DataFrame) -> pd.DataFrame:
    """Forward-fill, then clip causal spikes. No winsorization -- see above."""
    data = data.ffill().infer_objects()
    n_cells = n_clipped = 0
    for col in data.columns[1:]:
        series = pd.to_numeric(data[col], errors="coerce").astype("float64")
        if series.isna().all():
            continue
        n_cells += int(series.notna().sum())
        for o in _causal_spike_clips(series):
            series.iloc[o["index"]] = o["new_value"]
            n_clipped += 1
        data[col] = series
    if n_clipped:
        # Counted over POPULATED cells only. The previous counter used
        # `(series != winsorized).sum()`, and NaN != NaN is True, so every
        # leading-NaN cell was reported as cleaned -- MCAP logged 1,429
        # "winsorized", exactly its 1,429 NaN cells.
        logger.info("  cleaned: %d spikes clipped of %d populated cells (%.3f%%)",
                    n_clipped, n_cells, 100.0 * n_clipped / max(n_cells, 1))
    return data


def _forward_returns(data: pd.DataFrame, months: int) -> pd.DataFrame:
    returns = pd.DataFrame(index=data.index)
    for col in data.columns[1:]:
        values = pd.to_numeric(data[col], errors="coerce").astype("float64")
        returns[col] = (values.shift(-months) / values) - 1
    returns.insert(0, data.columns[0], data[data.columns[0]])
    return returns


def _trailing_returns(data: pd.DataFrame, months: int) -> pd.DataFrame:
    returns = pd.DataFrame(index=data.index)
    for col in data.columns[1:]:
        values = pd.to_numeric(data[col], errors="coerce").astype("float64")
        returns[col] = (values / values.shift(months)) - 1
    returns.insert(0, data.columns[0], data[data.columns[0]])
    return returns


# ── Commodity betas ──────────────────────────────────────────────────────────
# Ported 2026-08-21 from "A Complete/T2 Factor Timing Fuzzy/Step One Create
# T2Master.py" (commit 397207b, calculate_commodity_beta_and_scaled_returns).
#
# WHY: the Bloomberg workbook broadcasts ONE commodity price across all 34
# country columns. Cross-sectional dispersion is therefore exactly zero, the
# _CS z-score is 0/0, and Gold_CS / Copper_CS / Oil_CS / Agriculture_CS carry
# no information at all. Each country's BETA to the commodity does vary
# cross-sectionally (South Africa 0.81 vs U.S. 0.14 for Gold), so the _CS
# factor becomes meaningful.
#
# DELIBERATE DEVIATION FROM THE MONTHLY REPO: it uses rolling(120,
# min_periods=120) and then BACKFILLS the first 120 months with the first
# computable beta -- on the shipped file that is 121 of 319 months (37.9% of
# the sample, 2000-02 to 2010-02) carrying a beta estimated through Feb 2010.
# That is a ten-year look-ahead. Measured against a causal estimate over that
# block the ordering mostly survives (Gold rank-corr +0.80, Copper +0.79) but
# Oil does not: its backfill error 0.119 exceeds its own cross-sectional
# dispersion 0.075, and Agriculture falls to +0.05 in its worst month.
#
# ASADO uses rolling(120, min_periods=36) instead. Months 36-119 behave as an
# expanding window (honest partial estimates); from month 120 the construction
# is IDENTICAL to the monthly repo, so the two pipelines agree post-2010 rather
# than ASADO becoming a third definition. Cost: the first 36 months are NaN.
COMMODITY_SHEETS = ("Gold", "Copper", "Oil", "Agriculture")
BETA_WINDOW = 120
BETA_MIN_PERIODS = 36


def _country_monthly_returns(tot_ret: pd.DataFrame) -> pd.DataFrame:
    """1-month percentage returns per country from the Total Return Index."""
    out = pd.DataFrame(index=tot_ret.index)
    for col in tot_ret.columns[1:]:
        out[col] = pd.to_numeric(tot_ret[col], errors="coerce").astype("float64").pct_change()
    return out


def _commodity_betas(
    com_data: pd.DataFrame,
    country_1m_rets: pd.DataFrame,
    label: str = "",
    window: int = BETA_WINDOW,
    min_periods: int = BETA_MIN_PERIODS,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Trailing country betas to a commodity, and beta-scaled 12M commodity return.

    Returns (betas_df, scaled_12m_df), both in the standard
    (date column + one column per country) sheet shape.
    """
    # The input sheet broadcasts one price across every country column, so any
    # column is the commodity. Fail loudly if that ever stops being true, rather
    # than silently regressing to "Singapore's column".
    numeric = com_data.iloc[:, 1:].apply(pd.to_numeric, errors="coerce")
    xs_spread = numeric.std(axis=1).max()
    if pd.notna(xs_spread) and xs_spread > 1e-9:
        raise ValueError(
            f"Commodity sheet '{label}' is NOT broadcast across countries "
            f"(max cross-sectional std {xs_spread:.6g}). _commodity_betas assumes a "
            "single shared price series; a country-specific input needs a different "
            "code path."
        )

    com_price = pd.to_numeric(com_data.iloc[:, 1], errors="coerce").astype("float64")
    com_1m = com_price.pct_change()
    com_12m = (com_price / com_price.shift(12)) - 1

    betas = pd.DataFrame(index=com_data.index)
    for col in country_1m_rets.columns:
        y = country_1m_rets[col]
        cov = y.rolling(window, min_periods=min_periods).cov(com_1m)
        var = com_1m.rolling(window, min_periods=min_periods).var()
        betas[col] = (cov / var).astype("float64")

    # Late-inception countries have no own-history beta yet. Fill with the
    # CONTEMPORANEOUS cross-sectional mean (same date only -- no look-ahead).
    # Logged, not silent, per the data-handling rule.
    xs_mean = betas.mean(axis=1)
    fillable = betas.isna() & xs_mean.notna().values[:, None]
    n_filled = int(fillable.sum().sum())
    if n_filled:
        betas = betas.apply(lambda c: c.fillna(xs_mean))
        by_country = fillable.sum()
        worst = by_country[by_country > 0].sort_values(ascending=False)
        logger.info(
            "  %s betas: filled %d cells with the contemporaneous cross-sectional "
            "mean (late inception). Most affected: %s",
            label, n_filled,
            ", ".join(f"{k} {v}" for k, v in worst.head(5).items()),
        )
    still_na = int(betas.isna().sum().sum())
    logger.info("  %s betas: %d cells still NaN (pre-min_periods burn-in)", label, still_na)

    scaled = pd.DataFrame(index=com_data.index)
    for col in betas.columns:
        scaled[col] = (betas[col] * com_12m).astype("float64")

    date_col = com_data.columns[0]
    betas.insert(0, date_col, com_data[date_col])
    scaled.insert(0, date_col, com_data[date_col])
    return betas, scaled


def _change(data: pd.DataFrame, months: int, absolute: bool = False) -> pd.DataFrame:
    changes = pd.DataFrame(index=data.index)
    changes.insert(0, data.columns[0], data[data.columns[0]])
    for col in data.columns[1:]:
        values = pd.to_numeric(data[col], errors="coerce").astype("float64")
        historical = values.shift(months)
        changes[col] = (values - historical) if absolute else (values / historical) - 1
    return changes


def _ma_signal(price_data: pd.DataFrame, ma_data: pd.DataFrame) -> pd.DataFrame:
    signals = pd.DataFrame(index=price_data.index)
    signals.insert(0, price_data.columns[0], price_data[price_data.columns[0]])
    for col in price_data.columns[1:]:
        if col in ma_data.columns:
            prices = pd.to_numeric(price_data[col], errors="coerce").astype("float64")
            ma = pd.to_numeric(ma_data[col], errors="coerce").astype("float64")
            signals[col] = prices / ma
        else:
            signals[col] = np.nan
    return signals


def _load_bloomberg_sheet(
    excel_file: pd.ExcelFile, sheet_name: str
) -> pd.DataFrame:
    data = pd.read_excel(excel_file, sheet_name=sheet_name)
    data = data.iloc[2:].reset_index(drop=True)
    data.columns = COUNTRY_NAMES[: len(data.columns)]
    return _standardize_date(data)


# Factor sheets used to determine the master's latest data date (freshness gate).
FRESHNESS_REFERENCE_SHEETS = ("Tot Return Index ", "PX_LAST", "Gold", "Oil", "Inflation")


def check_bloomberg_freshness(bloomberg_file: Path = BLOOMBERG_FILE) -> pd.Timestamp:
    """Verify the Bloomberg master holds data for the last completed month.

    Returns the latest data date if fresh. Raises RuntimeError (FAIL IS FAIL)
    if the newest factor date falls in a month earlier than the last completed
    calendar month — so the caller STOPS the update. The workbook is now
    generated by ASADO (scripts/collect_t2_bloomberg.py, live blpapi), so a
    stale file means that collector did not run or Bloomberg was unreachable.
    Month-based comparison (not exact date) so a normal last-business-day
    reading (e.g. 2026-05-29) counts as current for May.
    """
    if not bloomberg_file.exists():
        raise FileNotFoundError(f"Bloomberg file not found: {bloomberg_file}")
    xl = pd.ExcelFile(str(bloomberg_file))
    latest: Optional[pd.Timestamp] = None
    for sh in FRESHNESS_REFERENCE_SHEETS:
        if sh not in xl.sheet_names:
            continue
        df = pd.read_excel(xl, sheet_name=sh, header=1)
        dates = pd.to_datetime(df[df.columns[0]], errors="coerce").dropna()
        if len(dates):
            m = dates.max()
            latest = m if latest is None else max(latest, m)
    if latest is None:
        raise RuntimeError(
            f"Could not read any dates from {bloomberg_file.name} "
            f"(reference sheets {FRESHNESS_REFERENCE_SHEETS}). Aborting T2 update."
        )
    today = pd.Timestamp(datetime.now().date())
    last_completed_month = (today.replace(day=1) - pd.Timedelta(days=1)).to_period("M")
    latest_month = latest.to_period("M")
    if latest_month < last_completed_month:
        raise RuntimeError(
            "Bloomberg master is STALE — refusing to run the T2 update.\n"
            f"  File:             {bloomberg_file}\n"
            f"  Latest data:      {latest.date()}  (month {latest_month})\n"
            f"  Expected through: {last_completed_month}  (last completed month)\n"
            "  -> ASADO generates this file via scripts/collect_t2_bloomberg.py.\n"
            "     Confirm the Bloomberg Terminal is up on the Parallels VM, then re-run\n"
            "     monthly_update.py (Stage 1 regenerates it), or run the collector directly:\n"
            '       conda run -p ".../OpusBloomberg/.venv" \\\n'
            "         python scripts/collect_t2_bloomberg.py"
        )
    logger.info("Bloomberg master freshness OK: latest %s (month %s >= required %s).",
                latest.date(), latest_month, last_completed_month)
    return latest


def build_t2_master() -> bytes:
    """
    Build T2 Master.xlsx in memory and return the raw bytes.
    Raises FileNotFoundError if Bloomberg or P2P input files are missing.
    Raises RuntimeError if the Bloomberg master is stale (freshness gate).
    """
    if not BLOOMBERG_FILE.exists():
        raise FileNotFoundError(f"Bloomberg file not found: {BLOOMBERG_FILE}")
    if not P2P_FILE.exists():
        raise FileNotFoundError(f"P2P file not found: {P2P_FILE}")

    # Freshness gate — stop loudly if the Bloomberg pull was not refreshed.
    check_bloomberg_freshness(BLOOMBERG_FILE)

    logger.info("Loading Bloomberg file: %s", BLOOMBERG_FILE)
    excel_file = pd.ExcelFile(str(BLOOMBERG_FILE))
    sheet_names = excel_file.sheet_names[1:]  # skip first sheet
    process_sheets = [s for s in sheet_names if "Mcap" not in s]

    # Load P2P
    logger.info("Loading P2P scores: %s", P2P_FILE)
    p2p_data = pd.read_excel(str(P2P_FILE), engine="openpyxl")
    if len(p2p_data.columns) <= len(COUNTRY_NAMES):
        p2p_data.columns = COUNTRY_NAMES[: len(p2p_data.columns)]
    else:
        raise ValueError("P2P file has more columns than expected COUNTRY_NAMES list")
    if "Country" in p2p_data.columns:
        p2p_data["Country"] = pd.to_datetime(p2p_data["Country"], errors="coerce")
        p2p_data = p2p_data.iloc[1:].reset_index(drop=True)

    # ── Write to an in-memory buffer ────────────────────────────────────────
    import io
    buf = io.BytesIO()

    with pd.ExcelWriter(buf, engine="xlsxwriter") as writer:

        # ── Forward returns ─────────────────────────────────────────────────
        logger.info("Processing Tot Return Index → forward + trailing returns")
        tot_ret = _load_bloomberg_sheet(excel_file, "Tot Return Index ")
        trailing_dict: Dict[int, pd.DataFrame] = {}

        for months in [1, 3, 6, 9, 12]:
            _forward_returns(tot_ret, months).to_excel(
                writer, sheet_name=f"{months}MRet", index=False
            )

        for months in [1, 3, 12]:
            tr = _trailing_returns(tot_ret, months)
            tr.to_excel(writer, sheet_name=f"{months}MTR", index=False)
            trailing_dict[months] = tr

        # 12-1M spread
        country_col = trailing_dict[12]["Country"]
        spread = trailing_dict[12].drop("Country", axis=1).subtract(
            trailing_dict[1].drop("Country", axis=1)
        )
        spread.insert(0, "Country", country_col)
        spread.to_excel(writer, sheet_name="12-1MTR", index=False)

        # ── Commodity / FX / bond changes ───────────────────────────────────
        # Gold/Copper/Oil/Agriculture are NOT here any more -- they are written
        # as betas below. Leaving them would also collide on the "Gold 12" etc.
        # sheet names and make xlsxwriter raise.
        change_specs = {
            "Currency": (12, False),
            "10Yr Bond": (12, True), "Best EPS": (36, False),
            "Trailing EPS": (36, False),
        }
        for sn, (months, absolute) in change_specs.items():
            if sn in excel_file.sheet_names:
                logger.info("  %s %d-month change", sn, months)
                data = _load_bloomberg_sheet(excel_file, sn)
                _change(data, months, absolute).to_excel(
                    writer, sheet_name=f"{sn} {months}", index=False
                )

        # ── Commodity betas (replaces the raw 12-month price change) ────────
        logger.info("Processing commodity betas (rolling %d, min_periods %d)",
                    BETA_WINDOW, BETA_MIN_PERIODS)
        country_1m = _country_monthly_returns(tot_ret)
        for sn in COMMODITY_SHEETS:
            if sn not in excel_file.sheet_names:
                logger.warning("  commodity sheet %s missing from Bloomberg master", sn)
                continue
            logger.info("  %s", sn)
            com = _load_bloomberg_sheet(excel_file, sn)
            betas, scaled = _commodity_betas(com, country_1m, label=sn)
            betas.to_excel(writer, sheet_name=sn, index=False)
            scaled.to_excel(writer, sheet_name=f"{sn} 12", index=False)

        # ── 120MA Signal ────────────────────────────────────────────────────
        if "PX_LAST" in excel_file.sheet_names and "120MA" in excel_file.sheet_names:
            logger.info("  120MA Signal")
            px = _load_bloomberg_sheet(excel_file, "PX_LAST")
            ma = _load_bloomberg_sheet(excel_file, "120MA")
            _ma_signal(px, ma).to_excel(writer, sheet_name="120MA Signal", index=False)

        # ── All other sheets (cleaned copies) ──────────────────────────────
        for sn in sheet_names:
            if sn in COMMODITY_SHEETS:
                # Already written above as betas. Skipping also keeps the betas
                # out of _clean_sheet, whose full-sample winsorizer is still
                # look-ahead pending the docs/T2_CAUSAL_CLEANING_2026-08-21.md
                # decision -- letting it touch them would re-inject the very
                # leak the rolling window removes.
                continue
            logger.info("  sheet: %s", sn)
            data = pd.read_excel(excel_file, sheet_name=sn)
            data = data.iloc[2:].reset_index(drop=True)
            if sn == "MCAP Adj":
                data = data.iloc[:400].copy()
            data.columns = COUNTRY_NAMES[: len(data.columns)]
            data = _standardize_date(data)
            if sn in process_sheets:
                data = _clean_sheet(data)
            data.to_excel(writer, sheet_name=sn, index=False)

        # ── P2P sheet ───────────────────────────────────────────────────────
        p2p_data.to_excel(writer, sheet_name="P2P", index=False)
        logger.info("P2P sheet written")

    buf.seek(0)
    return buf.read()


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--skip-p2p", action="store_true",
                    help="Skip P2P download and use existing P2P_Country_Historical_Scores.xlsx")
    ap.add_argument("--dry-run", action="store_true",
                    help="Preview only — no files written")
    ap.add_argument("--check", action="store_true",
                    help="Report on existing output files without rebuilding")
    ap.add_argument("--force", action="store_true",
                    help="Rebuild even if all 3 T2 Master.xlsx outputs are newer than inputs")
    ap.add_argument("--check-freshness", action="store_true",
                    help="Only run the Bloomberg-master freshness gate; exit non-zero if stale")
    args = ap.parse_args()

    # ── Freshness-only mode (early gate for monthly_update) ───────────────────
    if args.check_freshness:
        try:
            latest = check_bloomberg_freshness(BLOOMBERG_FILE)
            print(f"OK: Bloomberg master is fresh (latest {latest.date()}).")
            return 0
        except (RuntimeError, FileNotFoundError) as exc:
            print(str(exc))
            return 1

    # ── Up-to-date guard ──────────────────────────────────────────────────
    # Inputs: BLOOMBERG_FILE, P2P_FILE, ASSET_LIST_FILE
    # Outputs: 3× T2 Master.xlsx
    # If every output exists and is newer than every input, skip the entire run.
    if not args.force and not args.dry_run and not args.check:
        try:
            inputs = [BLOOMBERG_FILE, ASSET_LIST_FILE]
            if P2P_FILE.exists():
                inputs.append(P2P_FILE)
            input_mtimes = [p.stat().st_mtime for p in inputs if p.exists()]
            output_mtimes = [d.stat().st_mtime for d in T2_MASTER_DESTINATIONS if d.exists()]
            if (len(output_mtimes) == len(T2_MASTER_DESTINATIONS)
                    and input_mtimes
                    and min(output_mtimes) >= max(input_mtimes)):
                logger.info(
                    "All 3 T2 Master.xlsx outputs are newer than every input "
                    "(Bloomberg / AssetList / P2P). Skipping. Use --force to rebuild."
                )
                return 0
        except Exception as e:
            logger.warning("Up-to-date check failed (%s) — proceeding to rebuild.", e)

    if args.check:
        for dest in T2_MASTER_DESTINATIONS:
            if dest.exists():
                stat = dest.stat()
                logger.info("T2 Master.xlsx: %.1f MB, modified %s → %s",
                            stat.st_size / 1_048_576,
                            datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
                            dest)
            else:
                logger.warning("Missing: %s", dest)
        if P2P_FILE.exists():
            stat = P2P_FILE.stat()
            logger.info("P2P scores: %.0f KB, modified %s",
                        stat.st_size / 1024,
                        datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S"))
        else:
            logger.warning("P2P file missing: %s", P2P_FILE)
        return 0

    # ── Phase 1: P2P ────────────────────────────────────────────────────────
    if not args.skip_p2p:
        logger.info("=== PHASE 1: P2P Score Calculation ===")
        if args.dry_run:
            logger.info("[dry-run] Would download ETF prices and compute P2P scores → %s", P2P_FILE)
        else:
            try:
                p2p_df = build_p2p_scores()
                save_p2p(p2p_df)
            except Exception as e:
                logger.error("P2P calculation failed: %s", e)
                logger.error("Use --skip-p2p to proceed with existing P2P file")
                return 1
    else:
        if not P2P_FILE.exists():
            logger.error("--skip-p2p specified but P2P file not found: %s", P2P_FILE)
            return 1
        logger.info("P2P phase skipped — using existing: %s", P2P_FILE)

    # ── Phase 2: T2 Master ──────────────────────────────────────────────────
    logger.info("=== PHASE 2: T2 Master Generation ===")
    if args.dry_run:
        logger.info("[dry-run] Would build T2 Master.xlsx from %s + %s",
                    BLOOMBERG_FILE, P2P_FILE)
        for dest in T2_MASTER_DESTINATIONS:
            logger.info("[dry-run] Would write → %s", dest)
        return 0

    try:
        workbook_bytes = build_t2_master()
    except Exception as e:
        logger.error("T2 Master build failed: %s", e)
        return 1

    # Write to all destinations atomically (tmp → rename)
    for dest in T2_MASTER_DESTINATIONS:
        tmp = dest.with_suffix(".tmp.xlsx")
        try:
            tmp.write_bytes(workbook_bytes)
            tmp.replace(dest)
            size_mb = dest.stat().st_size / 1_048_576
            logger.info("Wrote %.1f MB → %s", size_mb, dest)
        except Exception as e:
            logger.error("Failed to write %s: %s", dest, e)
            if tmp.exists():
                tmp.unlink()
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
